FROM node:20-alpine AS base

# Stage 1: Install dependencies
FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# Stage 2: Build
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time environment variables (needed for next.config.ts env embedding)
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG N8N_WEBHOOK_URL
ARG N8N_WEBHOOK_SECRET
ARG AWS_SES_REGION
ARG AWS_SES_FROM_EMAIL
ARG AWS_SES_FROM_NAME
ARG AWS_SES_REPLY_TO_EMAIL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG STRIPE_SECRET_KEY
ARG STRIPE_PROFESSIONAL_PRICE_ID
ARG STRIPE_AGENCY_PRICE_ID
ARG STRIPE_WEBHOOK_SECRET
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_CLARITY_PROJECT_ID
ARG NEXT_PUBLIC_SENTRY_DSN
ARG SENTRY_ORG
ARG SENTRY_PROJECT

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV N8N_WEBHOOK_URL=$N8N_WEBHOOK_URL
ENV N8N_WEBHOOK_SECRET=$N8N_WEBHOOK_SECRET
ENV AWS_SES_REGION=$AWS_SES_REGION
ENV AWS_SES_FROM_EMAIL=$AWS_SES_FROM_EMAIL
ENV AWS_SES_FROM_NAME=$AWS_SES_FROM_NAME
ENV AWS_SES_REPLY_TO_EMAIL=$AWS_SES_REPLY_TO_EMAIL
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV STRIPE_PROFESSIONAL_PRICE_ID=$STRIPE_PROFESSIONAL_PRICE_ID
ENV STRIPE_AGENCY_PRICE_ID=$STRIPE_AGENCY_PRICE_ID
ENV STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_CLARITY_PROJECT_ID=$NEXT_PUBLIC_CLARITY_PROJECT_ID
ENV NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN
ENV SENTRY_ORG=$SENTRY_ORG
ENV SENTRY_PROJECT=$SENTRY_PROJECT

RUN npm run build

# Stage 3: Production runner
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

# All secrets are embedded at build time via next.config.ts env property
# This is required for Next.js standalone mode to access them at runtime

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
